spring:
  main:
    allow-bean-definition-overriding: true

  shardingsphere:
    datasource:
      names: test
      test:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://server_mysql:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        username: hddroot
        password: hddmysql

    sharding:
      tables:
        test_user:
          table-strategy:
            inline:
              sharding-column: userId
              algorithm-expression: test_user_$->{(int)(userId / 10)}

    props:
      sql.show: true


mybatis-plus:
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
